name: CoinsToMail
version: 1.6.0-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.coinstomail.Main
description: Paypal email/coin emailer.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  cashout:
  arena:
  duel:
    aliases: [1v1]
  createkit:
    aliases: [kit]
  coinstomail:
permissions:
  cointstomail.admin:
    default: op